### ISSUE TITLE
bubble bobble updateplayers 3 times?

### ISSUE THREAD

**Issue by therevills** [Pakz001/Raylib-Examples#1]
Why is updateplayers called 3 times?

https://github.com/Pakz001/Raylib-Examples/blob/9f8e529d426048cd34786426d7f3725c832572cb/games/bubblebobble.c#L240

**Comment by Pakz001** [comment]
This I did to make the player move faster. This function moves the player 1 pixel at a time and checks collision with the tilemap at every pixel change. If I move the player 3 pixels at a time it could move inside a tile. So I just call the updateplayer 3 times to make sure this does not happen!

**Comment by therevills** [comment]
Thanks for the answer, when I've done those kind of things I've either checked the tile space before moving or I've used a bresenham line to check if a collision is going to happen.
